spring:
  datasource:
    url: jdbc:mysql://localhost:3306/panda-quiz?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
